/**
 *
 *  Client.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Client.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::poctime;

const std::string Client::Cols::_id = "\"id\"";
const std::string Client::Cols::_street = "\"street\"";
const std::string Client::Cols::_number = "\"number\"";
const std::string Client::Cols::_complement = "\"complement\"";
const std::string Client::Cols::_neighborhood = "\"neighborhood\"";
const std::string Client::Cols::_city = "\"city\"";
const std::string Client::Cols::_state = "\"state\"";
const std::string Client::Cols::_zip_code = "\"zip_code\"";
const std::string Client::Cols::_country = "\"country\"";
const std::string Client::Cols::_state_code = "\"state_code\"";
const std::string Client::Cols::_client_email = "\"client_email\"";
const std::string Client::Cols::_deleted = "\"deleted\"";
const std::string Client::Cols::_person_id = "\"person_id\"";
const std::string Client::primaryKeyName = "id";
const bool Client::hasPrimaryKey = true;
const std::string Client::tableName = "\"client\"";

const std::vector<typename Client::MetaData> Client::metaData_ = {
    {"id", "int64_t", "bigint", 8, 0, 1, 1},
    {"street", "std::string", "character varying", 255, 0, 0, 0},
    {"number", "std::string", "character varying", 255, 0, 0, 0},
    {"complement", "std::string", "character varying", 255, 0, 0, 0},
    {"neighborhood", "std::string", "character varying", 255, 0, 0, 0},
    {"city", "std::string", "character varying", 255, 0, 0, 0},
    {"state", "std::string", "character varying", 255, 0, 0, 0},
    {"zip_code", "std::string", "character varying", 255, 0, 0, 0},
    {"country", "std::string", "character varying", 255, 0, 0, 0},
    {"state_code", "std::string", "character varying", 255, 0, 0, 0},
    {"client_email", "std::string", "character varying", 255, 0, 0, 0},
    {"deleted", "bool", "boolean", 1, 0, 0, 1},
    {"person_id", "int64_t", "bigint", 8, 0, 0, 0}
};

const std::string &Client::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

Client::Client(const Row &r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if (!r["street"].isNull()) {
            street_ = std::make_shared<std::string>(r["street"].as<std::string>());
        }
        if (!r["number"].isNull()) {
            number_ = std::make_shared<std::string>(r["number"].as<std::string>());
        }
        if (!r["complement"].isNull()) {
            complement_ = std::make_shared<std::string>(r["complement"].as<std::string>());
        }
        if (!r["neighborhood"].isNull()) {
            neighborhood_ = std::make_shared<std::string>(r["neighborhood"].as<std::string>());
        }
        if (!r["city"].isNull()) {
            city_ = std::make_shared<std::string>(r["city"].as<std::string>());
        }
        if (!r["state"].isNull()) {
            state_ = std::make_shared<std::string>(r["state"].as<std::string>());
        }
        if (!r["zip_code"].isNull()) {
            zipCode_ = std::make_shared<std::string>(r["zip_code"].as<std::string>());
        }
        if (!r["country"].isNull()) {
            country_ = std::make_shared<std::string>(r["country"].as<std::string>());
        }
        if (!r["state_code"].isNull()) {
            stateCode_ = std::make_shared<std::string>(r["state_code"].as<std::string>());
        }
        if (!r["client_email"].isNull()) {
            clientEmail_ = std::make_shared<std::string>(r["client_email"].as<std::string>());
        }
        if (!r["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(r["deleted"].as<bool>());
        }
        if (!r["person_id"].isNull()) {
            personId_ = std::make_shared<int64_t>(r["person_id"].as<int64_t>());
        }
    } else {
        size_t offset = (size_t) indexOffset;
        if (offset + 13 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            street_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            number_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            complement_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if (!r[index].isNull()) {
            neighborhood_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull()) {
            city_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if (!r[index].isNull()) {
            state_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if (!r[index].isNull()) {
            zipCode_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if (!r[index].isNull()) {
            country_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if (!r[index].isNull()) {
            stateCode_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if (!r[index].isNull()) {
            clientEmail_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if (!r[index].isNull()) {
            deleted_ = std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 12;
        if (!r[index].isNull()) {
            personId_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
    }
}

Client::Client(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 13) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            street_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            number_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            complement_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            neighborhood_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            city_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            state_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            zipCode_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            country_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            stateCode_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            clientEmail_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
        dirtyFlag_[11] = true;
        if (!pJson[pMasqueradingVector[11]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[11]].asBool());
        }
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
        dirtyFlag_[12] = true;
        if (!pJson[pMasqueradingVector[12]].isNull()) {
            personId_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[12]].asInt64());
        }
    }
}

Client::Client(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("street")) {
        dirtyFlag_[1] = true;
        if (!pJson["street"].isNull()) {
            street_ = std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if (pJson.isMember("number")) {
        dirtyFlag_[2] = true;
        if (!pJson["number"].isNull()) {
            number_ = std::make_shared<std::string>(pJson["number"].asString());
        }
    }
    if (pJson.isMember("complement")) {
        dirtyFlag_[3] = true;
        if (!pJson["complement"].isNull()) {
            complement_ = std::make_shared<std::string>(pJson["complement"].asString());
        }
    }
    if (pJson.isMember("neighborhood")) {
        dirtyFlag_[4] = true;
        if (!pJson["neighborhood"].isNull()) {
            neighborhood_ = std::make_shared<std::string>(pJson["neighborhood"].asString());
        }
    }
    if (pJson.isMember("city")) {
        dirtyFlag_[5] = true;
        if (!pJson["city"].isNull()) {
            city_ = std::make_shared<std::string>(pJson["city"].asString());
        }
    }
    if (pJson.isMember("state")) {
        dirtyFlag_[6] = true;
        if (!pJson["state"].isNull()) {
            state_ = std::make_shared<std::string>(pJson["state"].asString());
        }
    }
    if (pJson.isMember("zip_code")) {
        dirtyFlag_[7] = true;
        if (!pJson["zip_code"].isNull()) {
            zipCode_ = std::make_shared<std::string>(pJson["zip_code"].asString());
        }
    }
    if (pJson.isMember("country")) {
        dirtyFlag_[8] = true;
        if (!pJson["country"].isNull()) {
            country_ = std::make_shared<std::string>(pJson["country"].asString());
        }
    }
    if (pJson.isMember("state_code")) {
        dirtyFlag_[9] = true;
        if (!pJson["state_code"].isNull()) {
            stateCode_ = std::make_shared<std::string>(pJson["state_code"].asString());
        }
    }
    if (pJson.isMember("client_email")) {
        dirtyFlag_[10] = true;
        if (!pJson["client_email"].isNull()) {
            clientEmail_ = std::make_shared<std::string>(pJson["client_email"].asString());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[11] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("person_id")) {
        dirtyFlag_[12] = true;
        if (!pJson["person_id"].isNull()) {
            personId_ = std::make_shared<int64_t>((int64_t) pJson["person_id"].asInt64());
        }
    }
}

void Client::updateByMasqueradedJson(const Json::Value &pJson,
                                     const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 13) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            street_ = std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            number_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            complement_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            neighborhood_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            city_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
        dirtyFlag_[6] = true;
        if (!pJson[pMasqueradingVector[6]].isNull()) {
            state_ = std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
        dirtyFlag_[7] = true;
        if (!pJson[pMasqueradingVector[7]].isNull()) {
            zipCode_ = std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
        dirtyFlag_[8] = true;
        if (!pJson[pMasqueradingVector[8]].isNull()) {
            country_ = std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
        dirtyFlag_[9] = true;
        if (!pJson[pMasqueradingVector[9]].isNull()) {
            stateCode_ = std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
        dirtyFlag_[10] = true;
        if (!pJson[pMasqueradingVector[10]].isNull()) {
            clientEmail_ = std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
        dirtyFlag_[11] = true;
        if (!pJson[pMasqueradingVector[11]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[11]].asBool());
        }
    }
    if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
        dirtyFlag_[12] = true;
        if (!pJson[pMasqueradingVector[12]].isNull()) {
            personId_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[12]].asInt64());
        }
    }
}

void Client::updateByJson(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("street")) {
        dirtyFlag_[1] = true;
        if (!pJson["street"].isNull()) {
            street_ = std::make_shared<std::string>(pJson["street"].asString());
        }
    }
    if (pJson.isMember("number")) {
        dirtyFlag_[2] = true;
        if (!pJson["number"].isNull()) {
            number_ = std::make_shared<std::string>(pJson["number"].asString());
        }
    }
    if (pJson.isMember("complement")) {
        dirtyFlag_[3] = true;
        if (!pJson["complement"].isNull()) {
            complement_ = std::make_shared<std::string>(pJson["complement"].asString());
        }
    }
    if (pJson.isMember("neighborhood")) {
        dirtyFlag_[4] = true;
        if (!pJson["neighborhood"].isNull()) {
            neighborhood_ = std::make_shared<std::string>(pJson["neighborhood"].asString());
        }
    }
    if (pJson.isMember("city")) {
        dirtyFlag_[5] = true;
        if (!pJson["city"].isNull()) {
            city_ = std::make_shared<std::string>(pJson["city"].asString());
        }
    }
    if (pJson.isMember("state")) {
        dirtyFlag_[6] = true;
        if (!pJson["state"].isNull()) {
            state_ = std::make_shared<std::string>(pJson["state"].asString());
        }
    }
    if (pJson.isMember("zip_code")) {
        dirtyFlag_[7] = true;
        if (!pJson["zip_code"].isNull()) {
            zipCode_ = std::make_shared<std::string>(pJson["zip_code"].asString());
        }
    }
    if (pJson.isMember("country")) {
        dirtyFlag_[8] = true;
        if (!pJson["country"].isNull()) {
            country_ = std::make_shared<std::string>(pJson["country"].asString());
        }
    }
    if (pJson.isMember("state_code")) {
        dirtyFlag_[9] = true;
        if (!pJson["state_code"].isNull()) {
            stateCode_ = std::make_shared<std::string>(pJson["state_code"].asString());
        }
    }
    if (pJson.isMember("client_email")) {
        dirtyFlag_[10] = true;
        if (!pJson["client_email"].isNull()) {
            clientEmail_ = std::make_shared<std::string>(pJson["client_email"].asString());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[11] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("person_id")) {
        dirtyFlag_[12] = true;
        if (!pJson["person_id"].isNull()) {
            personId_ = std::make_shared<int64_t>((int64_t) pJson["person_id"].asInt64());
        }
    }
}

const int64_t &Client::getValueOfId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (id_)
        return *id_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Client::getId() const noexcept {
    return id_;
}

void Client::setId(const int64_t &pId) noexcept {
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Client::PrimaryKeyType &Client::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const std::string &Client::getValueOfStreet() const noexcept {
    static const std::string defaultValue = std::string();
    if (street_)
        return *street_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getStreet() const noexcept {
    return street_;
}

void Client::setStreet(const std::string &pStreet) noexcept {
    street_ = std::make_shared<std::string>(pStreet);
    dirtyFlag_[1] = true;
}

void Client::setStreet(std::string &&pStreet) noexcept {
    street_ = std::make_shared<std::string>(std::move(pStreet));
    dirtyFlag_[1] = true;
}

void Client::setStreetToNull() noexcept {
    street_.reset();
    dirtyFlag_[1] = true;
}

const std::string &Client::getValueOfNumber() const noexcept {
    static const std::string defaultValue = std::string();
    if (number_)
        return *number_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getNumber() const noexcept {
    return number_;
}

void Client::setNumber(const std::string &pNumber) noexcept {
    number_ = std::make_shared<std::string>(pNumber);
    dirtyFlag_[2] = true;
}

void Client::setNumber(std::string &&pNumber) noexcept {
    number_ = std::make_shared<std::string>(std::move(pNumber));
    dirtyFlag_[2] = true;
}

void Client::setNumberToNull() noexcept {
    number_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Client::getValueOfComplement() const noexcept {
    static const std::string defaultValue = std::string();
    if (complement_)
        return *complement_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getComplement() const noexcept {
    return complement_;
}

void Client::setComplement(const std::string &pComplement) noexcept {
    complement_ = std::make_shared<std::string>(pComplement);
    dirtyFlag_[3] = true;
}

void Client::setComplement(std::string &&pComplement) noexcept {
    complement_ = std::make_shared<std::string>(std::move(pComplement));
    dirtyFlag_[3] = true;
}

void Client::setComplementToNull() noexcept {
    complement_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Client::getValueOfNeighborhood() const noexcept {
    static const std::string defaultValue = std::string();
    if (neighborhood_)
        return *neighborhood_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getNeighborhood() const noexcept {
    return neighborhood_;
}

void Client::setNeighborhood(const std::string &pNeighborhood) noexcept {
    neighborhood_ = std::make_shared<std::string>(pNeighborhood);
    dirtyFlag_[4] = true;
}

void Client::setNeighborhood(std::string &&pNeighborhood) noexcept {
    neighborhood_ = std::make_shared<std::string>(std::move(pNeighborhood));
    dirtyFlag_[4] = true;
}

void Client::setNeighborhoodToNull() noexcept {
    neighborhood_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Client::getValueOfCity() const noexcept {
    static const std::string defaultValue = std::string();
    if (city_)
        return *city_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getCity() const noexcept {
    return city_;
}

void Client::setCity(const std::string &pCity) noexcept {
    city_ = std::make_shared<std::string>(pCity);
    dirtyFlag_[5] = true;
}

void Client::setCity(std::string &&pCity) noexcept {
    city_ = std::make_shared<std::string>(std::move(pCity));
    dirtyFlag_[5] = true;
}

void Client::setCityToNull() noexcept {
    city_.reset();
    dirtyFlag_[5] = true;
}

const std::string &Client::getValueOfState() const noexcept {
    static const std::string defaultValue = std::string();
    if (state_)
        return *state_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getState() const noexcept {
    return state_;
}

void Client::setState(const std::string &pState) noexcept {
    state_ = std::make_shared<std::string>(pState);
    dirtyFlag_[6] = true;
}

void Client::setState(std::string &&pState) noexcept {
    state_ = std::make_shared<std::string>(std::move(pState));
    dirtyFlag_[6] = true;
}

void Client::setStateToNull() noexcept {
    state_.reset();
    dirtyFlag_[6] = true;
}

const std::string &Client::getValueOfZipCode() const noexcept {
    static const std::string defaultValue = std::string();
    if (zipCode_)
        return *zipCode_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getZipCode() const noexcept {
    return zipCode_;
}

void Client::setZipCode(const std::string &pZipCode) noexcept {
    zipCode_ = std::make_shared<std::string>(pZipCode);
    dirtyFlag_[7] = true;
}

void Client::setZipCode(std::string &&pZipCode) noexcept {
    zipCode_ = std::make_shared<std::string>(std::move(pZipCode));
    dirtyFlag_[7] = true;
}

void Client::setZipCodeToNull() noexcept {
    zipCode_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Client::getValueOfCountry() const noexcept {
    static const std::string defaultValue = std::string();
    if (country_)
        return *country_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getCountry() const noexcept {
    return country_;
}

void Client::setCountry(const std::string &pCountry) noexcept {
    country_ = std::make_shared<std::string>(pCountry);
    dirtyFlag_[8] = true;
}

void Client::setCountry(std::string &&pCountry) noexcept {
    country_ = std::make_shared<std::string>(std::move(pCountry));
    dirtyFlag_[8] = true;
}

void Client::setCountryToNull() noexcept {
    country_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Client::getValueOfStateCode() const noexcept {
    static const std::string defaultValue = std::string();
    if (stateCode_)
        return *stateCode_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getStateCode() const noexcept {
    return stateCode_;
}

void Client::setStateCode(const std::string &pStateCode) noexcept {
    stateCode_ = std::make_shared<std::string>(pStateCode);
    dirtyFlag_[9] = true;
}

void Client::setStateCode(std::string &&pStateCode) noexcept {
    stateCode_ = std::make_shared<std::string>(std::move(pStateCode));
    dirtyFlag_[9] = true;
}

void Client::setStateCodeToNull() noexcept {
    stateCode_.reset();
    dirtyFlag_[9] = true;
}

const std::string &Client::getValueOfClientEmail() const noexcept {
    static const std::string defaultValue = std::string();
    if (clientEmail_)
        return *clientEmail_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Client::getClientEmail() const noexcept {
    return clientEmail_;
}

void Client::setClientEmail(const std::string &pClientEmail) noexcept {
    clientEmail_ = std::make_shared<std::string>(pClientEmail);
    dirtyFlag_[10] = true;
}

void Client::setClientEmail(std::string &&pClientEmail) noexcept {
    clientEmail_ = std::make_shared<std::string>(std::move(pClientEmail));
    dirtyFlag_[10] = true;
}

void Client::setClientEmailToNull() noexcept {
    clientEmail_.reset();
    dirtyFlag_[10] = true;
}

const bool &Client::getValueOfDeleted() const noexcept {
    static const bool defaultValue = bool();
    if (deleted_)
        return *deleted_;
    return defaultValue;
}

const std::shared_ptr<bool> &Client::getDeleted() const noexcept {
    return deleted_;
}

void Client::setDeleted(const bool &pDeleted) noexcept {
    deleted_ = std::make_shared<bool>(pDeleted);
    dirtyFlag_[11] = true;
}

const int64_t &Client::getValueOfPersonId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (personId_)
        return *personId_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Client::getPersonId() const noexcept {
    return personId_;
}

void Client::setPersonId(const int64_t &pPersonId) noexcept {
    personId_ = std::make_shared<int64_t>(pPersonId);
    dirtyFlag_[12] = true;
}

void Client::setPersonIdToNull() noexcept {
    personId_.reset();
    dirtyFlag_[12] = true;
}

void Client::updateId(const uint64_t id) {
}

const std::vector<std::string> &Client::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
        "id",
        "street",
        "number",
        "complement",
        "neighborhood",
        "city",
        "state",
        "zip_code",
        "country",
        "state_code",
        "client_email",
        "deleted",
        "person_id"
    };
    return inCols;
}

void Client::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getStreet()) {
            binder << getValueOfStreet();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getNumber()) {
            binder << getValueOfNumber();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getComplement()) {
            binder << getValueOfComplement();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getNeighborhood()) {
            binder << getValueOfNeighborhood();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getCity()) {
            binder << getValueOfCity();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getState()) {
            binder << getValueOfState();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getZipCode()) {
            binder << getValueOfZipCode();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getCountry()) {
            binder << getValueOfCountry();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getStateCode()) {
            binder << getValueOfStateCode();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getClientEmail()) {
            binder << getValueOfClientEmail();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[11]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[12]) {
        if (getPersonId()) {
            binder << getValueOfPersonId();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Client::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[0]) {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4]) {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5]) {
        ret.push_back(getColumnName(5));
    }
    if (dirtyFlag_[6]) {
        ret.push_back(getColumnName(6));
    }
    if (dirtyFlag_[7]) {
        ret.push_back(getColumnName(7));
    }
    if (dirtyFlag_[8]) {
        ret.push_back(getColumnName(8));
    }
    if (dirtyFlag_[9]) {
        ret.push_back(getColumnName(9));
    }
    if (dirtyFlag_[10]) {
        ret.push_back(getColumnName(10));
    }
    if (dirtyFlag_[11]) {
        ret.push_back(getColumnName(11));
    }
    if (dirtyFlag_[12]) {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void Client::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getStreet()) {
            binder << getValueOfStreet();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getNumber()) {
            binder << getValueOfNumber();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getComplement()) {
            binder << getValueOfComplement();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getNeighborhood()) {
            binder << getValueOfNeighborhood();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getCity()) {
            binder << getValueOfCity();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[6]) {
        if (getState()) {
            binder << getValueOfState();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[7]) {
        if (getZipCode()) {
            binder << getValueOfZipCode();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[8]) {
        if (getCountry()) {
            binder << getValueOfCountry();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[9]) {
        if (getStateCode()) {
            binder << getValueOfStateCode();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[10]) {
        if (getClientEmail()) {
            binder << getValueOfClientEmail();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[11]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[12]) {
        if (getPersonId()) {
            binder << getValueOfPersonId();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value Client::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getStreet()) {
        ret["street"] = getValueOfStreet();
    } else {
        ret["street"] = Json::Value();
    }
    if (getNumber()) {
        ret["number"] = getValueOfNumber();
    } else {
        ret["number"] = Json::Value();
    }
    if (getComplement()) {
        ret["complement"] = getValueOfComplement();
    } else {
        ret["complement"] = Json::Value();
    }
    if (getNeighborhood()) {
        ret["neighborhood"] = getValueOfNeighborhood();
    } else {
        ret["neighborhood"] = Json::Value();
    }
    if (getCity()) {
        ret["city"] = getValueOfCity();
    } else {
        ret["city"] = Json::Value();
    }
    if (getState()) {
        ret["state"] = getValueOfState();
    } else {
        ret["state"] = Json::Value();
    }
    if (getZipCode()) {
        ret["zip_code"] = getValueOfZipCode();
    } else {
        ret["zip_code"] = Json::Value();
    }
    if (getCountry()) {
        ret["country"] = getValueOfCountry();
    } else {
        ret["country"] = Json::Value();
    }
    if (getStateCode()) {
        ret["state_code"] = getValueOfStateCode();
    } else {
        ret["state_code"] = Json::Value();
    }
    if (getClientEmail()) {
        ret["client_email"] = getValueOfClientEmail();
    } else {
        ret["client_email"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getPersonId()) {
        ret["person_id"] = (Json::Int64) getValueOfPersonId();
    } else {
        ret["person_id"] = Json::Value();
    }
    return ret;
}

std::string Client::toString() const {
    return toJson().toStyledString();
}

Json::Value Client::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 13) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::Int64) getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getStreet()) {
                ret[pMasqueradingVector[1]] = getValueOfStreet();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getNumber()) {
                ret[pMasqueradingVector[2]] = getValueOfNumber();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getComplement()) {
                ret[pMasqueradingVector[3]] = getValueOfComplement();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (getNeighborhood()) {
                ret[pMasqueradingVector[4]] = getValueOfNeighborhood();
            } else {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (getCity()) {
                ret[pMasqueradingVector[5]] = getValueOfCity();
            } else {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (getState()) {
                ret[pMasqueradingVector[6]] = getValueOfState();
            } else {
                ret[pMasqueradingVector[6]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (getZipCode()) {
                ret[pMasqueradingVector[7]] = getValueOfZipCode();
            } else {
                ret[pMasqueradingVector[7]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (getCountry()) {
                ret[pMasqueradingVector[8]] = getValueOfCountry();
            } else {
                ret[pMasqueradingVector[8]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (getStateCode()) {
                ret[pMasqueradingVector[9]] = getValueOfStateCode();
            } else {
                ret[pMasqueradingVector[9]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (getClientEmail()) {
                ret[pMasqueradingVector[10]] = getValueOfClientEmail();
            } else {
                ret[pMasqueradingVector[10]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[11].empty()) {
            if (getDeleted()) {
                ret[pMasqueradingVector[11]] = getValueOfDeleted();
            } else {
                ret[pMasqueradingVector[11]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[12].empty()) {
            if (getPersonId()) {
                ret[pMasqueradingVector[12]] = (Json::Int64) getValueOfPersonId();
            } else {
                ret[pMasqueradingVector[12]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getStreet()) {
        ret["street"] = getValueOfStreet();
    } else {
        ret["street"] = Json::Value();
    }
    if (getNumber()) {
        ret["number"] = getValueOfNumber();
    } else {
        ret["number"] = Json::Value();
    }
    if (getComplement()) {
        ret["complement"] = getValueOfComplement();
    } else {
        ret["complement"] = Json::Value();
    }
    if (getNeighborhood()) {
        ret["neighborhood"] = getValueOfNeighborhood();
    } else {
        ret["neighborhood"] = Json::Value();
    }
    if (getCity()) {
        ret["city"] = getValueOfCity();
    } else {
        ret["city"] = Json::Value();
    }
    if (getState()) {
        ret["state"] = getValueOfState();
    } else {
        ret["state"] = Json::Value();
    }
    if (getZipCode()) {
        ret["zip_code"] = getValueOfZipCode();
    } else {
        ret["zip_code"] = Json::Value();
    }
    if (getCountry()) {
        ret["country"] = getValueOfCountry();
    } else {
        ret["country"] = Json::Value();
    }
    if (getStateCode()) {
        ret["state_code"] = getValueOfStateCode();
    } else {
        ret["state_code"] = Json::Value();
    }
    if (getClientEmail()) {
        ret["client_email"] = getValueOfClientEmail();
    } else {
        ret["client_email"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getPersonId()) {
        ret["person_id"] = (Json::Int64) getValueOfPersonId();
    } else {
        ret["person_id"] = Json::Value();
    }
    return ret;
}

bool Client::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    } else {
        err = "The id column cannot be null";
        return false;
    }
    if (pJson.isMember("street")) {
        if (!validJsonOfField(1, "street", pJson["street"], err, true))
            return false;
    }
    if (pJson.isMember("number")) {
        if (!validJsonOfField(2, "number", pJson["number"], err, true))
            return false;
    }
    if (pJson.isMember("complement")) {
        if (!validJsonOfField(3, "complement", pJson["complement"], err, true))
            return false;
    }
    if (pJson.isMember("neighborhood")) {
        if (!validJsonOfField(4, "neighborhood", pJson["neighborhood"], err, true))
            return false;
    }
    if (pJson.isMember("city")) {
        if (!validJsonOfField(5, "city", pJson["city"], err, true))
            return false;
    }
    if (pJson.isMember("state")) {
        if (!validJsonOfField(6, "state", pJson["state"], err, true))
            return false;
    }
    if (pJson.isMember("zip_code")) {
        if (!validJsonOfField(7, "zip_code", pJson["zip_code"], err, true))
            return false;
    }
    if (pJson.isMember("country")) {
        if (!validJsonOfField(8, "country", pJson["country"], err, true))
            return false;
    }
    if (pJson.isMember("state_code")) {
        if (!validJsonOfField(9, "state_code", pJson["state_code"], err, true))
            return false;
    }
    if (pJson.isMember("client_email")) {
        if (!validJsonOfField(10, "client_email", pJson["client_email"], err, true))
            return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(11, "deleted", pJson["deleted"], err, true))
            return false;
    } else {
        err = "The deleted column cannot be null";
        return false;
    }
    if (pJson.isMember("person_id")) {
        if (!validJsonOfField(12, "person_id", pJson["person_id"], err, true))
            return false;
    }
    return true;
}

bool Client::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err) {
    if (pMasqueradingVector.size() != 13) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (pJson.isMember(pMasqueradingVector[4])) {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (pJson.isMember(pMasqueradingVector[5])) {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[6].empty()) {
            if (pJson.isMember(pMasqueradingVector[6])) {
                if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[7].empty()) {
            if (pJson.isMember(pMasqueradingVector[7])) {
                if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[8].empty()) {
            if (pJson.isMember(pMasqueradingVector[8])) {
                if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[9].empty()) {
            if (pJson.isMember(pMasqueradingVector[9])) {
                if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[10].empty()) {
            if (pJson.isMember(pMasqueradingVector[10])) {
                if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[11].empty()) {
            if (pJson.isMember(pMasqueradingVector[11])) {
                if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[11] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[12].empty()) {
            if (pJson.isMember(pMasqueradingVector[12])) {
                if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                    return false;
            }
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Client::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("street")) {
        if (!validJsonOfField(1, "street", pJson["street"], err, false))
            return false;
    }
    if (pJson.isMember("number")) {
        if (!validJsonOfField(2, "number", pJson["number"], err, false))
            return false;
    }
    if (pJson.isMember("complement")) {
        if (!validJsonOfField(3, "complement", pJson["complement"], err, false))
            return false;
    }
    if (pJson.isMember("neighborhood")) {
        if (!validJsonOfField(4, "neighborhood", pJson["neighborhood"], err, false))
            return false;
    }
    if (pJson.isMember("city")) {
        if (!validJsonOfField(5, "city", pJson["city"], err, false))
            return false;
    }
    if (pJson.isMember("state")) {
        if (!validJsonOfField(6, "state", pJson["state"], err, false))
            return false;
    }
    if (pJson.isMember("zip_code")) {
        if (!validJsonOfField(7, "zip_code", pJson["zip_code"], err, false))
            return false;
    }
    if (pJson.isMember("country")) {
        if (!validJsonOfField(8, "country", pJson["country"], err, false))
            return false;
    }
    if (pJson.isMember("state_code")) {
        if (!validJsonOfField(9, "state_code", pJson["state_code"], err, false))
            return false;
    }
    if (pJson.isMember("client_email")) {
        if (!validJsonOfField(10, "client_email", pJson["client_email"], err, false))
            return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(11, "deleted", pJson["deleted"], err, false))
            return false;
    }
    if (pJson.isMember("person_id")) {
        if (!validJsonOfField(12, "person_id", pJson["person_id"], err, false))
            return false;
    }
    return true;
}

bool Client::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err) {
    if (pMasqueradingVector.size() != 13) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
                return false;
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
                return false;
        }
        if (!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6])) {
            if (!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
                return false;
        }
        if (!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7])) {
            if (!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
                return false;
        }
        if (!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8])) {
            if (!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
                return false;
        }
        if (!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9])) {
            if (!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
                return false;
        }
        if (!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10])) {
            if (!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
                return false;
        }
        if (!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11])) {
            if (!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
                return false;
        }
        if (!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12])) {
            if (!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
                return false;
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Client::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 5:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 6:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 7:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 8:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 9:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 10:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 11:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isBool()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 12:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}