/**
 *
 *  Client.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace poctime
{

class Client
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _street;
        static const std::string _number;
        static const std::string _complement;
        static const std::string _neighborhood;
        static const std::string _city;
        static const std::string _state;
        static const std::string _zip_code;
        static const std::string _country;
        static const std::string _state_code;
        static const std::string _client_email;
        static const std::string _deleted;
        static const std::string _person_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Client(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Client(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Client(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Client() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int64_t &pId) noexcept;

    /**  For column street  */
    ///Get the value of the column street, returns the default value if the column is null
    const std::string &getValueOfStreet() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStreet() const noexcept;
    ///Set the value of the column street
    void setStreet(const std::string &pStreet) noexcept;
    void setStreet(std::string &&pStreet) noexcept;
    void setStreetToNull() noexcept;

    /**  For column number  */
    ///Get the value of the column number, returns the default value if the column is null
    const std::string &getValueOfNumber() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNumber() const noexcept;
    ///Set the value of the column number
    void setNumber(const std::string &pNumber) noexcept;
    void setNumber(std::string &&pNumber) noexcept;
    void setNumberToNull() noexcept;

    /**  For column complement  */
    ///Get the value of the column complement, returns the default value if the column is null
    const std::string &getValueOfComplement() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getComplement() const noexcept;
    ///Set the value of the column complement
    void setComplement(const std::string &pComplement) noexcept;
    void setComplement(std::string &&pComplement) noexcept;
    void setComplementToNull() noexcept;

    /**  For column neighborhood  */
    ///Get the value of the column neighborhood, returns the default value if the column is null
    const std::string &getValueOfNeighborhood() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNeighborhood() const noexcept;
    ///Set the value of the column neighborhood
    void setNeighborhood(const std::string &pNeighborhood) noexcept;
    void setNeighborhood(std::string &&pNeighborhood) noexcept;
    void setNeighborhoodToNull() noexcept;

    /**  For column city  */
    ///Get the value of the column city, returns the default value if the column is null
    const std::string &getValueOfCity() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCity() const noexcept;
    ///Set the value of the column city
    void setCity(const std::string &pCity) noexcept;
    void setCity(std::string &&pCity) noexcept;
    void setCityToNull() noexcept;

    /**  For column state  */
    ///Get the value of the column state, returns the default value if the column is null
    const std::string &getValueOfState() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getState() const noexcept;
    ///Set the value of the column state
    void setState(const std::string &pState) noexcept;
    void setState(std::string &&pState) noexcept;
    void setStateToNull() noexcept;

    /**  For column zip_code  */
    ///Get the value of the column zip_code, returns the default value if the column is null
    const std::string &getValueOfZipCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getZipCode() const noexcept;
    ///Set the value of the column zip_code
    void setZipCode(const std::string &pZipCode) noexcept;
    void setZipCode(std::string &&pZipCode) noexcept;
    void setZipCodeToNull() noexcept;

    /**  For column country  */
    ///Get the value of the column country, returns the default value if the column is null
    const std::string &getValueOfCountry() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCountry() const noexcept;
    ///Set the value of the column country
    void setCountry(const std::string &pCountry) noexcept;
    void setCountry(std::string &&pCountry) noexcept;
    void setCountryToNull() noexcept;

    /**  For column state_code  */
    ///Get the value of the column state_code, returns the default value if the column is null
    const std::string &getValueOfStateCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getStateCode() const noexcept;
    ///Set the value of the column state_code
    void setStateCode(const std::string &pStateCode) noexcept;
    void setStateCode(std::string &&pStateCode) noexcept;
    void setStateCodeToNull() noexcept;

    /**  For column client_email  */
    ///Get the value of the column client_email, returns the default value if the column is null
    const std::string &getValueOfClientEmail() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientEmail() const noexcept;
    ///Set the value of the column client_email
    void setClientEmail(const std::string &pClientEmail) noexcept;
    void setClientEmail(std::string &&pClientEmail) noexcept;
    void setClientEmailToNull() noexcept;

    /**  For column deleted  */
    ///Get the value of the column deleted, returns the default value if the column is null
    const bool &getValueOfDeleted() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getDeleted() const noexcept;
    ///Set the value of the column deleted
    void setDeleted(const bool &pDeleted) noexcept;

    /**  For column person_id  */
    ///Get the value of the column person_id, returns the default value if the column is null
    const int64_t &getValueOfPersonId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getPersonId() const noexcept;
    ///Set the value of the column person_id
    void setPersonId(const int64_t &pPersonId) noexcept;
    void setPersonIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
  private:
    friend drogon::orm::Mapper<Client>;
    friend drogon::orm::BaseBuilder<Client, true, true>;
    friend drogon::orm::BaseBuilder<Client, true, false>;
    friend drogon::orm::BaseBuilder<Client, false, true>;
    friend drogon::orm::BaseBuilder<Client, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Client>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int64_t> id_;
    std::shared_ptr<std::string> street_;
    std::shared_ptr<std::string> number_;
    std::shared_ptr<std::string> complement_;
    std::shared_ptr<std::string> neighborhood_;
    std::shared_ptr<std::string> city_;
    std::shared_ptr<std::string> state_;
    std::shared_ptr<std::string> zipCode_;
    std::shared_ptr<std::string> country_;
    std::shared_ptr<std::string> stateCode_;
    std::shared_ptr<std::string> clientEmail_;
    std::shared_ptr<bool> deleted_;
    std::shared_ptr<int64_t> personId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "id,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "street,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "number,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "complement,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "neighborhood,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "city,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "state,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "zip_code,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "country,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "state_code,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "client_email,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "deleted,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "person_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace poctime
} // namespace drogon_model
