/**
 *
 *  Economicgroup.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon {
    namespace orm {
        class DbClient;
        using DbClientPtr = std::shared_ptr<DbClient>;
    }
}

namespace drogon_model {
    namespace poctime {
        class Economicgroup {
        public:
            struct Cols {
                static const std::string _id;
                static const std::string _deleted;
                static const std::string _description;
                static const std::string _name;
                static const std::string _organization_ids;
                static const std::string _search_vector;
            };

            static const int primaryKeyNumber;
            static const std::string tableName;
            static const bool hasPrimaryKey;
            static const std::string primaryKeyName;
            using PrimaryKeyType = int64_t;

            const PrimaryKeyType &getPrimaryKey() const;

            /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
            explicit Economicgroup(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

            /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
            explicit Economicgroup(const Json::Value &pJson) noexcept(false);

            /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
            Economicgroup(const Json::Value &pJson,
                          const std::vector<std::string> &pMasqueradingVector) noexcept(false);

            Economicgroup() = default;

            void updateByJson(const Json::Value &pJson) noexcept(false);

            void updateByMasqueradedJson(const Json::Value &pJson,
                                         const std::vector<std::string> &pMasqueradingVector) noexcept(false);

            static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);

            static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err);

            static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);

            static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                                         const std::vector<std::string> &pMasqueradingVector,
                                                         std::string &err);

            static bool validJsonOfField(size_t index,
                                         const std::string &fieldName,
                                         const Json::Value &pJson,
                                         std::string &err,
                                         bool isForCreation);

            /**  For column id  */
            ///Get the value of the column id, returns the default value if the column is null
            const int64_t &getValueOfId() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<int64_t> &getId() const noexcept;

            ///Set the value of the column id
            void setId(const int64_t &pId) noexcept;

            /**  For column deleted  */
            ///Get the value of the column deleted, returns the default value if the column is null
            const bool &getValueOfDeleted() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<bool> &getDeleted() const noexcept;

            ///Set the value of the column deleted
            void setDeleted(const bool &pDeleted) noexcept;

            /**  For column description  */
            ///Get the value of the column description, returns the default value if the column is null
            const std::string &getValueOfDescription() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string> &getDescription() const noexcept;

            ///Set the value of the column description
            void setDescription(const std::string &pDescription) noexcept;

            void setDescription(std::string &&pDescription) noexcept;

            void setDescriptionToNull() noexcept;

            /**  For column name  */
            ///Get the value of the column name, returns the default value if the column is null
            const std::string &getValueOfName() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string> &getName() const noexcept;

            ///Set the value of the column name
            void setName(const std::string &pName) noexcept;

            void setName(std::string &&pName) noexcept;

            void setNameToNull() noexcept;

            /**  For column organization_ids  */
            ///Get the value of the column organization_ids, returns the default value if the column is null
            const std::string &getValueOfOrganization_ids() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string> &getOrganization_ids() const noexcept;

            ///Set the value of the column organization_ids
            void setOrganization_ids(const std::string &pOrganization_ids) noexcept;

            void setOrganization_ids(std::string &&pOrganization_ids) noexcept;

            /**  For column search_vector  */
            ///Get the value of the column search_vector, returns the default value if the column is null
            const std::string &getValueOfSearchVector() const noexcept;

            ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
            const std::shared_ptr<std::string> &getSearchVector() const noexcept;

            ///Set the value of the column search_vector
            void setSearchVector(const std::string &pSearchVector) noexcept;

            void setSearchVector(std::string &&pSearchVector) noexcept;

            void setSearchVectorToNull() noexcept;


            static size_t getColumnNumber() noexcept { return 6; }

            static const std::string &getColumnName(size_t index) noexcept(false);

            Json::Value toJson() const;

            std::string toString() const;

            Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;

            /// Relationship interfaces
        private:
            friend drogon::orm::Mapper<Economicgroup>;
            friend drogon::orm::BaseBuilder<Economicgroup, true, true>;
            friend drogon::orm::BaseBuilder<Economicgroup, true, false>;
            friend drogon::orm::BaseBuilder<Economicgroup, false, true>;
            friend drogon::orm::BaseBuilder<Economicgroup, false, false>;
#ifdef __cpp_impl_coroutine
            friend drogon::orm::CoroMapper<Economicgroup>;
#endif
            static const std::vector<std::string> &insertColumns() noexcept;

            void outputArgs(drogon::orm::internal::SqlBinder &binder) const;

            const std::vector<std::string> updateColumns() const;

            void updateArgs(drogon::orm::internal::SqlBinder &binder) const;

            ///For mysql or sqlite3
            void updateId(const uint64_t id);

            std::shared_ptr<int64_t> id_;
            std::shared_ptr<bool> deleted_;
            std::shared_ptr<std::string> description_;
            std::shared_ptr<std::string> name_;
            std::shared_ptr<std::string> organization_ids_;
            std::shared_ptr<std::string> searchVector_;

            struct MetaData {
                const std::string colName_;
                const std::string colType_;
                const std::string colDatabaseType_;
                const ssize_t colLength_;
                const bool isAutoVal_;
                const bool isPrimaryKey_;
                const bool notNull_;
            };

            static const std::vector<MetaData> metaData_;
            bool dirtyFlag_[6] = {false};

        public:
            static const std::string &sqlForFindingByPrimaryKey() {
                static const std::string sql = "select * from " + tableName + " where id = $1";
                return sql;
            }

            static const std::string &sqlForDeletingByPrimaryKey() {
                static const std::string sql = "delete from " + tableName + " where id = $1";
                return sql;
            }

            std::string sqlForInserting(bool &needSelection) const {
                std::string sql = "insert into " + tableName + " (";
                size_t parametersCount = 0;
                needSelection = false;
                if (dirtyFlag_[0]) {
                    sql += "id,";
                    ++parametersCount;
                }
                if (dirtyFlag_[1]) {
                    sql += "deleted,";
                    ++parametersCount;
                }
                if (dirtyFlag_[2]) {
                    sql += "description,";
                    ++parametersCount;
                }
                if (dirtyFlag_[3]) {
                    sql += "name,";
                    ++parametersCount;
                }
                if (dirtyFlag_[4]) {
                    sql += "organization_ids,";
                    ++parametersCount;
                }
                if (dirtyFlag_[5]) {
                    sql += "search_vector,";
                    ++parametersCount;
                }
                if (parametersCount > 0) {
                    sql[sql.length() - 1] = ')';
                    sql += " values (";
                } else
                    sql += ") values (";

                int placeholder = 1;
                char placeholderStr[64];
                size_t n = 0;
                if (dirtyFlag_[0]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[1]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[2]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[3]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[4]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (dirtyFlag_[5]) {
                    n = snprintf(placeholderStr, sizeof(placeholderStr), "$%d,", placeholder++);
                    sql.append(placeholderStr, n);
                }
                if (parametersCount > 0) {
                    sql.resize(sql.length() - 1);
                }
                if (needSelection) {
                    sql.append(") returning *");
                } else {
                    sql.append(1, ')');
                }
                LOG_TRACE << sql;
                return sql;
            }
        };
    } // namespace poctime
} // namespace drogon_model