/**
 *
 *  Person.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Person.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::poctime;

const std::string Person::Cols::_id = "\"id\"";
const std::string Person::Cols::_deleted = "\"deleted\"";
const std::string Person::Cols::_document = "\"document\"";
const std::string Person::Cols::_name = "\"name\"";
const std::string Person::primaryKeyName = "id";
const bool Person::hasPrimaryKey = true;
const std::string Person::tableName = "\"person\"";

const std::vector<typename Person::MetaData> Person::metaData_ = {
    {"id", "int64_t", "bigint", 8, 0, 1, 1},
    {"deleted", "bool", "boolean", 1, 0, 0, 1},
    {"document", "std::string", "jsonb", 0, 0, 0, 1},
    {"name", "std::string", "character varying", 255, 0, 0, 0}
};

const std::string &Person::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

Person::Person(const Row &r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if (!r["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(r["deleted"].as<bool>());
        }
        if (!r["document"].isNull()) {
            document_ = std::make_shared<std::string>(r["document"].as<std::string>());
        }
        if (!r["name"].isNull()) {
            name_ = std::make_shared<std::string>(r["name"].as<std::string>());
        }
    } else {
        size_t offset = (size_t) indexOffset;
        if (offset + 4 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            deleted_ = std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            document_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            name_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
    }
}

Person::Person(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 4) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            document_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

Person::Person(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[1] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("document")) {
        dirtyFlag_[2] = true;
        if (!pJson["document"].isNull()) {
            document_ = std::make_shared<std::string>(pJson["document"].asString());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[3] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
}

void Person::updateByMasqueradedJson(const Json::Value &pJson,
                                     const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 4) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            document_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
}

void Person::updateByJson(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[1] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("document")) {
        dirtyFlag_[2] = true;
        if (!pJson["document"].isNull()) {
            document_ = std::make_shared<std::string>(pJson["document"].asString());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[3] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
}

const int64_t &Person::getValueOfId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (id_)
        return *id_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Person::getId() const noexcept {
    return id_;
}

void Person::setId(const int64_t &pId) noexcept {
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Person::PrimaryKeyType &Person::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const bool &Person::getValueOfDeleted() const noexcept {
    static const bool defaultValue = bool();
    if (deleted_)
        return *deleted_;
    return defaultValue;
}

const std::shared_ptr<bool> &Person::getDeleted() const noexcept {
    return deleted_;
}

void Person::setDeleted(const bool &pDeleted) noexcept {
    deleted_ = std::make_shared<bool>(pDeleted);
    dirtyFlag_[1] = true;
}

const std::string &Person::getValueOfDocument() const noexcept {
    static const std::string defaultValue = std::string();
    if (document_)
        return *document_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Person::getDocument() const noexcept {
    return document_;
}

void Person::setDocument(const std::string &pDocument) noexcept {
    document_ = std::make_shared<std::string>(pDocument);
    dirtyFlag_[2] = true;
}

void Person::setDocument(std::string &&pDocument) noexcept {
    document_ = std::make_shared<std::string>(std::move(pDocument));
    dirtyFlag_[2] = true;
}

const std::string &Person::getValueOfName() const noexcept {
    static const std::string defaultValue = std::string();
    if (name_)
        return *name_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Person::getName() const noexcept {
    return name_;
}

void Person::setName(const std::string &pName) noexcept {
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[3] = true;
}

void Person::setName(std::string &&pName) noexcept {
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[3] = true;
}

void Person::setNameToNull() noexcept {
    name_.reset();
    dirtyFlag_[3] = true;
}

void Person::updateId(const uint64_t id) {
}

const std::vector<std::string> &Person::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
        "id",
        "deleted",
        "document",
        "name"
    };
    return inCols;
}

void Person::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getDocument()) {
            binder << getValueOfDocument();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Person::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[0]) {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    return ret;
}

void Person::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getDocument()) {
            binder << getValueOfDocument();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value Person::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getDocument()) {
        ret["document"] = getValueOfDocument();
    } else {
        ret["document"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    return ret;
}

std::string Person::toString() const {
    return toJson().toStyledString();
}

Json::Value Person::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 4) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::Int64) getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getDeleted()) {
                ret[pMasqueradingVector[1]] = getValueOfDeleted();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getDocument()) {
                ret[pMasqueradingVector[2]] = getValueOfDocument();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getName()) {
                ret[pMasqueradingVector[3]] = getValueOfName();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getDocument()) {
        ret["document"] = getValueOfDocument();
    } else {
        ret["document"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    return ret;
}

bool Person::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    } else {
        err = "The id column cannot be null";
        return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(1, "deleted", pJson["deleted"], err, true))
            return false;
    } else {
        err = "The deleted column cannot be null";
        return false;
    }
    if (pJson.isMember("document")) {
        if (!validJsonOfField(2, "document", pJson["document"], err, true))
            return false;
    } else {
        err = "The document column cannot be null";
        return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(3, "name", pJson["name"], err, true))
            return false;
    }
    return true;
}

bool Person::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err) {
    if (pMasqueradingVector.size() != 4) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[2] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                    return false;
            }
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Person::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(1, "deleted", pJson["deleted"], err, false))
            return false;
    }
    if (pJson.isMember("document")) {
        if (!validJsonOfField(2, "document", pJson["document"], err, false))
            return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(3, "name", pJson["name"], err, false))
            return false;
    }
    return true;
}

bool Person::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err) {
    if (pMasqueradingVector.size() != 4) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
                return false;
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Person::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isBool()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}
