/**
 *
 *  Product.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Product.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::poctime;

const std::string Product::Cols::_id = "\"id\"";
const std::string Product::Cols::_deleted = "\"deleted\"";
const std::string Product::Cols::_name = "\"name\"";
const std::string Product::Cols::_category_id = "\"category_id\"";
const std::string Product::Cols::_description = "\"description\"";
const std::string Product::Cols::_sku = "\"sku\"";
const std::string Product::primaryKeyName = "id";
const bool Product::hasPrimaryKey = true;
const std::string Product::tableName = "\"product\"";

const std::vector<typename Product::MetaData> Product::metaData_ = {
    {"id", "int64_t", "bigint", 8, 0, 1, 1},
    {"deleted", "bool", "boolean", 1, 0, 0, 1},
    {"name", "std::string", "character varying", 255, 0, 0, 0},
    {"category_id", "int64_t", "bigint", 8, 0, 0, 0},
    {"description", "std::string", "text", 0, 0, 0, 0},
    {"sku", "std::string", "character varying", 100, 0, 0, 0}
};

const std::string &Product::getColumnName(size_t index) noexcept(false) {
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}

Product::Product(const Row &r, const ssize_t indexOffset) noexcept {
    if (indexOffset < 0) {
        if (!r["id"].isNull()) {
            id_ = std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if (!r["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(r["deleted"].as<bool>());
        }
        if (!r["name"].isNull()) {
            name_ = std::make_shared<std::string>(r["name"].as<std::string>());
        }
        if (!r["category_id"].isNull()) {
            categoryId_ = std::make_shared<int64_t>(r["category_id"].as<int64_t>());
        }
        if (!r["description"].isNull()) {
            description_ = std::make_shared<std::string>(r["description"].as<std::string>());
        }
        if (!r["sku"].isNull()) {
            sku_ = std::make_shared<std::string>(r["sku"].as<std::string>());
        }
    } else {
        size_t offset = (size_t) indexOffset;
        if (offset + 6 > r.size()) {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if (!r[index].isNull()) {
            id_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if (!r[index].isNull()) {
            deleted_ = std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 2;
        if (!r[index].isNull()) {
            name_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if (!r[index].isNull()) {
            categoryId_ = std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 4;
        if (!r[index].isNull()) {
            description_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if (!r[index].isNull()) {
            sku_ = std::make_shared<std::string>(r[index].as<std::string>());
        }
    }
}

Product::Product(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 6) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        dirtyFlag_[0] = true;
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            categoryId_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            sku_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

Product::Product(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        dirtyFlag_[0] = true;
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[1] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[2] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("category_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["category_id"].isNull()) {
            categoryId_ = std::make_shared<int64_t>((int64_t) pJson["category_id"].asInt64());
        }
    }
    if (pJson.isMember("description")) {
        dirtyFlag_[4] = true;
        if (!pJson["description"].isNull()) {
            description_ = std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if (pJson.isMember("sku")) {
        dirtyFlag_[5] = true;
        if (!pJson["sku"].isNull()) {
            sku_ = std::make_shared<std::string>(pJson["sku"].asString());
        }
    }
}

void Product::updateByMasqueradedJson(const Json::Value &pJson,
                                      const std::vector<std::string> &pMasqueradingVector) noexcept(false) {
    if (pMasqueradingVector.size() != 6) {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
        if (!pJson[pMasqueradingVector[0]].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
        dirtyFlag_[1] = true;
        if (!pJson[pMasqueradingVector[1]].isNull()) {
            deleted_ = std::make_shared<bool>(pJson[pMasqueradingVector[1]].asBool());
        }
    }
    if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
        dirtyFlag_[2] = true;
        if (!pJson[pMasqueradingVector[2]].isNull()) {
            name_ = std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
        dirtyFlag_[3] = true;
        if (!pJson[pMasqueradingVector[3]].isNull()) {
            categoryId_ = std::make_shared<int64_t>((int64_t) pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
        dirtyFlag_[4] = true;
        if (!pJson[pMasqueradingVector[4]].isNull()) {
            description_ = std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
        dirtyFlag_[5] = true;
        if (!pJson[pMasqueradingVector[5]].isNull()) {
            sku_ = std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
}

void Product::updateByJson(const Json::Value &pJson) noexcept(false) {
    if (pJson.isMember("id")) {
        if (!pJson["id"].isNull()) {
            id_ = std::make_shared<int64_t>((int64_t) pJson["id"].asInt64());
        }
    }
    if (pJson.isMember("deleted")) {
        dirtyFlag_[1] = true;
        if (!pJson["deleted"].isNull()) {
            deleted_ = std::make_shared<bool>(pJson["deleted"].asBool());
        }
    }
    if (pJson.isMember("name")) {
        dirtyFlag_[2] = true;
        if (!pJson["name"].isNull()) {
            name_ = std::make_shared<std::string>(pJson["name"].asString());
        }
    }
    if (pJson.isMember("category_id")) {
        dirtyFlag_[3] = true;
        if (!pJson["category_id"].isNull()) {
            categoryId_ = std::make_shared<int64_t>((int64_t) pJson["category_id"].asInt64());
        }
    }
    if (pJson.isMember("description")) {
        dirtyFlag_[4] = true;
        if (!pJson["description"].isNull()) {
            description_ = std::make_shared<std::string>(pJson["description"].asString());
        }
    }
    if (pJson.isMember("sku")) {
        dirtyFlag_[5] = true;
        if (!pJson["sku"].isNull()) {
            sku_ = std::make_shared<std::string>(pJson["sku"].asString());
        }
    }
}

const int64_t &Product::getValueOfId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (id_)
        return *id_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Product::getId() const noexcept {
    return id_;
}

void Product::setId(const int64_t &pId) noexcept {
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}

const typename Product::PrimaryKeyType &Product::getPrimaryKey() const {
    assert(id_);
    return *id_;
}

const bool &Product::getValueOfDeleted() const noexcept {
    static const bool defaultValue = bool();
    if (deleted_)
        return *deleted_;
    return defaultValue;
}

const std::shared_ptr<bool> &Product::getDeleted() const noexcept {
    return deleted_;
}

void Product::setDeleted(const bool &pDeleted) noexcept {
    deleted_ = std::make_shared<bool>(pDeleted);
    dirtyFlag_[1] = true;
}

const std::string &Product::getValueOfName() const noexcept {
    static const std::string defaultValue = std::string();
    if (name_)
        return *name_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Product::getName() const noexcept {
    return name_;
}

void Product::setName(const std::string &pName) noexcept {
    name_ = std::make_shared<std::string>(pName);
    dirtyFlag_[2] = true;
}

void Product::setName(std::string &&pName) noexcept {
    name_ = std::make_shared<std::string>(std::move(pName));
    dirtyFlag_[2] = true;
}

void Product::setNameToNull() noexcept {
    name_.reset();
    dirtyFlag_[2] = true;
}

const int64_t &Product::getValueOfCategoryId() const noexcept {
    static const int64_t defaultValue = int64_t();
    if (categoryId_)
        return *categoryId_;
    return defaultValue;
}

const std::shared_ptr<int64_t> &Product::getCategoryId() const noexcept {
    return categoryId_;
}

void Product::setCategoryId(const int64_t &pCategoryId) noexcept {
    categoryId_ = std::make_shared<int64_t>(pCategoryId);
    dirtyFlag_[3] = true;
}

void Product::setCategoryIdToNull() noexcept {
    categoryId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Product::getValueOfDescription() const noexcept {
    static const std::string defaultValue = std::string();
    if (description_)
        return *description_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Product::getDescription() const noexcept {
    return description_;
}

void Product::setDescription(const std::string &pDescription) noexcept {
    description_ = std::make_shared<std::string>(pDescription);
    dirtyFlag_[4] = true;
}

void Product::setDescription(std::string &&pDescription) noexcept {
    description_ = std::make_shared<std::string>(std::move(pDescription));
    dirtyFlag_[4] = true;
}

void Product::setDescriptionToNull() noexcept {
    description_.reset();
    dirtyFlag_[4] = true;
}

const std::string &Product::getValueOfSku() const noexcept {
    static const std::string defaultValue = std::string();
    if (sku_)
        return *sku_;
    return defaultValue;
}

const std::shared_ptr<std::string> &Product::getSku() const noexcept {
    return sku_;
}

void Product::setSku(const std::string &pSku) noexcept {
    sku_ = std::make_shared<std::string>(pSku);
    dirtyFlag_[5] = true;
}

void Product::setSku(std::string &&pSku) noexcept {
    sku_ = std::make_shared<std::string>(std::move(pSku));
    dirtyFlag_[5] = true;
}

void Product::setSkuToNull() noexcept {
    sku_.reset();
    dirtyFlag_[5] = true;
}

void Product::updateId(const uint64_t id) {
}

const std::vector<std::string> &Product::insertColumns() noexcept {
    static const std::vector<std::string> inCols = {
        "id",
        "deleted",
        "name",
        "category_id",
        "description",
        "sku"
    };
    return inCols;
}

void Product::outputArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getCategoryId()) {
            binder << getValueOfCategoryId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getDescription()) {
            binder << getValueOfDescription();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getSku()) {
            binder << getValueOfSku();
        } else {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Product::updateColumns() const {
    std::vector<std::string> ret;
    if (dirtyFlag_[0]) {
        ret.push_back(getColumnName(0));
    }
    if (dirtyFlag_[1]) {
        ret.push_back(getColumnName(1));
    }
    if (dirtyFlag_[2]) {
        ret.push_back(getColumnName(2));
    }
    if (dirtyFlag_[3]) {
        ret.push_back(getColumnName(3));
    }
    if (dirtyFlag_[4]) {
        ret.push_back(getColumnName(4));
    }
    if (dirtyFlag_[5]) {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void Product::updateArgs(drogon::orm::internal::SqlBinder &binder) const {
    if (dirtyFlag_[0]) {
        if (getId()) {
            binder << getValueOfId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[1]) {
        if (getDeleted()) {
            binder << getValueOfDeleted();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[2]) {
        if (getName()) {
            binder << getValueOfName();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[3]) {
        if (getCategoryId()) {
            binder << getValueOfCategoryId();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[4]) {
        if (getDescription()) {
            binder << getValueOfDescription();
        } else {
            binder << nullptr;
        }
    }
    if (dirtyFlag_[5]) {
        if (getSku()) {
            binder << getValueOfSku();
        } else {
            binder << nullptr;
        }
    }
}

Json::Value Product::toJson() const {
    Json::Value ret;
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    if (getCategoryId()) {
        ret["category_id"] = (Json::Int64) getValueOfCategoryId();
    } else {
        ret["category_id"] = Json::Value();
    }
    if (getDescription()) {
        ret["description"] = getValueOfDescription();
    } else {
        ret["description"] = Json::Value();
    }
    if (getSku()) {
        ret["sku"] = getValueOfSku();
    } else {
        ret["sku"] = Json::Value();
    }
    return ret;
}

std::string Product::toString() const {
    return toJson().toStyledString();
}

Json::Value Product::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const {
    Json::Value ret;
    if (pMasqueradingVector.size() == 6) {
        if (!pMasqueradingVector[0].empty()) {
            if (getId()) {
                ret[pMasqueradingVector[0]] = (Json::Int64) getValueOfId();
            } else {
                ret[pMasqueradingVector[0]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (getDeleted()) {
                ret[pMasqueradingVector[1]] = getValueOfDeleted();
            } else {
                ret[pMasqueradingVector[1]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (getName()) {
                ret[pMasqueradingVector[2]] = getValueOfName();
            } else {
                ret[pMasqueradingVector[2]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (getCategoryId()) {
                ret[pMasqueradingVector[3]] = (Json::Int64) getValueOfCategoryId();
            } else {
                ret[pMasqueradingVector[3]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (getDescription()) {
                ret[pMasqueradingVector[4]] = getValueOfDescription();
            } else {
                ret[pMasqueradingVector[4]] = Json::Value();
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (getSku()) {
                ret[pMasqueradingVector[5]] = getValueOfSku();
            } else {
                ret[pMasqueradingVector[5]] = Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if (getId()) {
        ret["id"] = (Json::Int64) getValueOfId();
    } else {
        ret["id"] = Json::Value();
    }
    if (getDeleted()) {
        ret["deleted"] = getValueOfDeleted();
    } else {
        ret["deleted"] = Json::Value();
    }
    if (getName()) {
        ret["name"] = getValueOfName();
    } else {
        ret["name"] = Json::Value();
    }
    if (getCategoryId()) {
        ret["category_id"] = (Json::Int64) getValueOfCategoryId();
    } else {
        ret["category_id"] = Json::Value();
    }
    if (getDescription()) {
        ret["description"] = getValueOfDescription();
    } else {
        ret["description"] = Json::Value();
    }
    if (getSku()) {
        ret["sku"] = getValueOfSku();
    } else {
        ret["sku"] = Json::Value();
    }
    return ret;
}

bool Product::validateJsonForCreation(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    } else {
        err = "The id column cannot be null";
        return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(1, "deleted", pJson["deleted"], err, true))
            return false;
    } else {
        err = "The deleted column cannot be null";
        return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(2, "name", pJson["name"], err, true))
            return false;
    }
    if (pJson.isMember("category_id")) {
        if (!validJsonOfField(3, "category_id", pJson["category_id"], err, true))
            return false;
    }
    if (pJson.isMember("description")) {
        if (!validJsonOfField(4, "description", pJson["description"], err, true))
            return false;
    }
    if (pJson.isMember("sku")) {
        if (!validJsonOfField(5, "sku", pJson["sku"], err, true))
            return false;
    }
    return true;
}

bool Product::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err) {
    if (pMasqueradingVector.size() != 6) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty()) {
            if (pJson.isMember(pMasqueradingVector[0])) {
                if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[0] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[1].empty()) {
            if (pJson.isMember(pMasqueradingVector[1])) {
                if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                    return false;
            } else {
                err = "The " + pMasqueradingVector[1] + " column cannot be null";
                return false;
            }
        }
        if (!pMasqueradingVector[2].empty()) {
            if (pJson.isMember(pMasqueradingVector[2])) {
                if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[3].empty()) {
            if (pJson.isMember(pMasqueradingVector[3])) {
                if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[4].empty()) {
            if (pJson.isMember(pMasqueradingVector[4])) {
                if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                    return false;
            }
        }
        if (!pMasqueradingVector[5].empty()) {
            if (pJson.isMember(pMasqueradingVector[5])) {
                if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                    return false;
            }
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Product::validateJsonForUpdate(const Json::Value &pJson, std::string &err) {
    if (pJson.isMember("id")) {
        if (!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    } else {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if (pJson.isMember("deleted")) {
        if (!validJsonOfField(1, "deleted", pJson["deleted"], err, false))
            return false;
    }
    if (pJson.isMember("name")) {
        if (!validJsonOfField(2, "name", pJson["name"], err, false))
            return false;
    }
    if (pJson.isMember("category_id")) {
        if (!validJsonOfField(3, "category_id", pJson["category_id"], err, false))
            return false;
    }
    if (pJson.isMember("description")) {
        if (!validJsonOfField(4, "description", pJson["description"], err, false))
            return false;
    }
    if (pJson.isMember("sku")) {
        if (!validJsonOfField(5, "sku", pJson["sku"], err, false))
            return false;
    }
    return true;
}

bool Product::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                               const std::vector<std::string> &pMasqueradingVector,
                                               std::string &err) {
    if (pMasqueradingVector.size() != 6) {
        err = "Bad masquerading vector";
        return false;
    }
    try {
        if (!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0])) {
            if (!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
                return false;
        } else {
            err = "The value of primary key must be set in the json object for update";
            return false;
        }
        if (!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1])) {
            if (!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
                return false;
        }
        if (!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2])) {
            if (!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
                return false;
        }
        if (!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3])) {
            if (!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
                return false;
        }
        if (!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4])) {
            if (!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
                return false;
        }
        if (!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5])) {
            if (!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
                return false;
        }
    } catch (const Json::LogicError &e) {
        err = e.what();
        return false;
    }
    return true;
}

bool Product::validJsonOfField(size_t index,
                               const std::string &fieldName,
                               const Json::Value &pJson,
                               std::string &err,
                               bool isForCreation) {
    switch (index) {
        case 0:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 1:
            if (pJson.isNull()) {
                err = "The " + fieldName + " column cannot be null";
                return false;
            }
            if (!pJson.isBool()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 2:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 255) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 255)";
                return false;
            }
            break;
        case 3:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isInt64()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 4:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            break;
        case 5:
            if (pJson.isNull()) {
                return true;
            }
            if (!pJson.isString()) {
                err = "Type error in the " + fieldName + " field";
                return false;
            }
            if (pJson.isString() && pJson.asString().size() > 100) {
                err = "String length exceeds limit for the " +
                      fieldName +
                      " field (the maximum value is 100)";
                return false;
            }
            break;
        default:
            err = "Internal error in the server";
            return false;
    }
    return true;
}